{
  "openapi":"3.0.2",
  "info": {
    "title":"Cargo Terminal",
    "version":"1.0",
    "license": {
      "name": "MIT",
      "url": "https://raw.githubusercontent.com/DiegoVictor/cargo-terminal-api/master/LICENSE"
    }
  },
  "servers": [
    {
      "url":"http://localhost:3333/v1"
    }
  ],
  "paths": {
    "/drivers": {
      "get": {
        "tags": ["Drivers"],
        "parameters": [
          {
            "in": "query",
            "name": "active",
            "required": false,
            "schema": {
              "type": "integer",
              "enum": [0, 1]
            },
            "example": 0
          },
          {
            "in": "query",
            "name": "vehicle",
            "required": false,
            "schema": {
              "type": "integer",
              "enum": [0, 1]
            },
            "example": 0
          },
          {
            "in": "query",
            "name": "page",
            "required": false,
            "schema": {
              "type": "integer"
            },
            "example": 1
          }
        ],
        "responses": {
          "200": {
            "description": "Lists drivers",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "allOf": [
                      {
                        "title": "Driver",
                        "properties": {
                          "_id": {
                            "type": "string"
                          }
                        }
                      },
                      {
                        "$ref": "#/components/schemas/Driver"
                      }
                    ]
                  }
                },
                "example": [
                  {
                    "_id": "60bbb289d63cfd06c06cd3b9",
                    "vehicle_id": "60bbb21dd63cfd06c06cd3b8",
                    "active": true,
                    "cpf": "41921630563",
                    "name": "John Doe",
                    "phone": "+55 679 924356443",
                    "birthday": "136-12-25",
                    "gender": "M",
                    "cnh_number": "DJUKPTRF9EH178332",
                    "cnh_type": "A"
                  }
                ]
              }
            },
            "headers": {
              "X-Total-Count": {
                "description": "Total number of registries in the database",
                "schema": {
                  "type": "integer"
                }
              },
              "Link": {
                "description": "Next, Previous, First and Last page's urls",
                "schema": {
                  "type": "string"
                }
              }
            }
          }
        }
      },
      "post": {
        "tags": ["Drivers"],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "allOf": [
                  {
                    "$ref": "#/components/schemas/Driver"
                  },
                  {
                    "title": "Driver",
                    "required": [
                      "cpf",
                      "name",
                      "phone",
                      "birthday",
                      "gender",
                      "cnh_number",
                      "cnh_type",
                      "vehicle_id"
                    ]
                  }
                ]
              },
              "example": {
                "cpf": "99999999999",
                "name": "John Doe",
                "phone": "+55 679 924356443",
                "birthday": "2000-01-01",
                "gender": "M",
                "cnh_number": "DJUKPTRF9EH178332",
                "cnh_type": "A",
                "vehicle_id": "6137997ac96e4a1570797420"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Create a new driver",
            "content": {
              "application/json": {
                "schema": {
                  "allOf": [
                    {
                      "title": "Driver",
                      "properties": {
                        "_id": {
                          "type": "string"
                        }
                      }
                    },
                    {
                      "$ref": "#/components/schemas/Driver"
                    }
                  ]
                },
                "example": {
                  "_id": "61379eedc0d2453b5835beed",
                  "active": true,
                  "cpf": "99999999999",
                  "name": "John Doe",
                  "phone": "+55 679 924356443",
                  "birthday": "1999-12-31",
                  "gender": "M",
                  "cnh_number": "DJUKPTRF9EH178332",
                  "cnh_type": "A",
                  "vehicle_id": "6137997ac96e4a1570797420"
                }
              }
            }
          },
          "404": {
            "description": "Vehicle not found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                },
                "example": {
                  "statusCode": 404,
                  "error": "Not Found",
                  "message": "Vehicle not found",
                  "code": 244,
                  "docs": "https://github.com/DiegoVictor/cargo-terminal-api#errors-reference"
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "Driver": {
        "properties": {
          "vehicle_id": {
            "type": "string"
          },
          "active": {
            "type": "boolean"
          },
          "cpf": {
            "type": "string"
          },
          "name": {
            "type": "string"
          },
          "phone": {
            "type": "string"
          },
          "birthday": {
            "type": "string"
          },
          "gender": {
            "type": "string"
          },
          "cnh_number": {
            "type": "string"
          },
          "cnh_type": {
            "type": "string"
          }
        }
      },
    }
  }
}
